name: Release

on:
  release:
    types: [ published ]

jobs:
  release:
  
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v2
      - name: Zip each directory
        run: |
          powershell { gci | % { Compress-Archive "$($_.FullName)\*" "$($_.Name).${{ github.event.release.tag_name }}.zip" } }
      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          file: "*.zip"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
